CREATE TABLE teams (
    team_id SERIAL PRIMARY KEY
    , team_name VARCHAR(255) NOT NULL UNIQUE
    , created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
    , updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_teams_team_name ON teams(team_name);